### PR TITLE
Update axidmatest.c

### PR DESCRIPTION
**Pull request by skantonovich**

### CODE REVIEW

**Comment by radheyxilinx** [comment]
@skantonovich , thanks for the patch. Pull request is not accepted in current workflow.
Please send out the patch to git@xilinx.com.  Refer to this wiki for additional information-https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/18842172/Create+and+Submit+a+Patch

In patch add a description on the problem and what this patch do to fix it.

**Comment by michalsimek** [comment]
Your patch has missing description that's why please resubmit it also with adding SoB line to git@xilinx.com. 

FYI: Please do not submit a Pull Request via github.  Our project makes use of
mailing lists for patch submission and review.  For more details please see
https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/18842172/Create+and+Submit+a+Patch

**Comment by michalsimek** [comment]
@skantonovich - Can you please at least tell us your name that we can give you credit for this patch?

**Comment by skantonovich** [comment]
Stanislav Antonovich, or what name required?
My account at github can be tracked from history.

As I remember the patch contains one line of code to remove. This line
seems useless to me.

Sorry for delays.

чт, 14 мая 2020 г., 10:13 Michal Šimek <notifications@github.com>:

**Comment by michalsimek** [comment]
ok and also email address please.

**Comment by skantonovich** [comment]
skantonovich@gmail.com
This also used on xilinx.com

чт, 14 мая 2020 г., 10:49 Michal Šimek <notifications@github.com>:

**Comment by michalsimek** [comment]
Thanks. My colleague massaged commit message and the patch will be available unfortunately after 2020.1 is tagged.

**Comment by skantonovich** [comment]
OK.
I'm glad after all it will be applied

чт, 14 мая 2020 г. в 15:03, Michal Šimek <notifications@github.com>:

**Pull request closed without merging**
