### PR TITLE
Update README1

### PR DESCRIPTION
**Pull request by Daniperea**
Please do not submit a Pull Request via github.  Our project makes use of
mailing lists for patch submission and review.  For more details please see
https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/18842172/Create+and+Submit+a+Patch

### CODE REVIEW

**Comment by fga333** [comment]
您好，您的邮件我已经收到，我会尽快给您回复。
 
谢谢！

**Comment by Coding-xinxiangwanji2017** [comment]
Hi，您好：    我收到了您邮件，等我看完邮件以后，第一时间给您回复。

**Review by Daniperea — COMMENTED** [review]
- - [ ]

**Comment by michalsimek** [comment]
Please do not submit a Pull Request via github. Our project makes use of
mailing lists for patch submission and review. For more details please see
https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/18842172/Create+and+Submit+a+Patch

not sure what else you need from us.

**Pull request closed without merging**
