### PR TITLE
AXI DMA: Bugfix: callback is invoked too early.

### PR DESCRIPTION
**Pull request by jeremytrimble**
In reference to issue #54:

For scatter-gather dmaengine operations, it seems to make sense that a
dmaengine-compatible driver should invoke your callback after the last
transfer of the scatter-gather operation has taken place.  However, it
seems that the xilinx_axidma.c driver is invoking it immediately after
the first transfer, rather than the last.  If the scatter-gather
operation consists of multiple transfers, those other transfers may
still be in-progress at the time when the callback is invoked, which is
probably not what dmaengine API users would expect.

This patch modifies the xilinx_dma_prep_slave_sg() call to return the
"last" dma_async_tx_descriptor associated with a scatter-gather
operation, rather than the first, so that the callback is invoked after
the last scatter-gather transfer has taken place.

May want to consider increasing IRQThreshold in *DMACR when submitting
such a group of descriptors to the DMA, in order to reduce interrupt
overhead that could not possibly result in a callback invocation.

### CODE REVIEW

**Comment by D953i** [comment]
jeremytrimble - thank you! Saved me lots of time.

I can confirm the issue and that this patch fixed the problem in my case too.

**Comment by jeremytrimble** [comment]
michalsimek -- Do you see an issue with the patch or do you just not accept pull requests through github?

I just found this page: http://www.wiki.xilinx.com/Create+and+Submit+a+Patch.  I'll try and submit a patch through that process soon if you don't see any issues.

**Comment by michalsimek** [comment]
On 05/22/2015 02:18 PM, Jeremy Trimble wrote:
> michalsimek -- Do you see an issue with the patch or do you just not accept pull requests through github?
> 
> I just found this page: http://www.wiki.xilinx.com/Create+and+Submit+a+Patch.  I'll try and submit a patch through that process soon if you don't see any issues.

yes, I am not taking pull request via github at all.
Please send the patch to git@xilinx.com.

Thanks,
Michal

**Comment by vanmierlo** [comment]
@jeremytrimble did you ever send the patch? Or was this fixed in some other way in the meantime?

**Comment by jeremytrimble** [comment]
@vanmierlo Xilinx did a complete overhaul on the AXI DMA driver after this, so I didn't submit it as it seemed like a moot point.  I personally haven't upgraded to the latest driver yet (I've been just forward-porting my patched version of the older driver), so I haven't tried out the new one yet to see if it still has this problem.  I'll probably upgrade to the latest sometime in the next month, so I'll re-evaluate then.

**Pull request closed without merging**
